src/presenter/controllers/actors.py
from flask import Flask, Blueprint, jsonify, render_template, url_for, request, redirect, flash
import ipdb
import json

actors_blueprint = Blueprint("actors", __name__)

from presenter.app import app, db, ALLOWED_EXTENSIONS, UPLOAD_FOLDER
from presenter.models.actor import Actor


actor_headers = ["name", "url", "filmography_movie_name", "filmography_url"]


def allowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


@actors_blueprint.route("/actors/", defaults={"page_nr": 1})
# @actors_blueprint.route("/actors/page=<int:page_nr>&items=<int:item_nr>", methods=["GET", "POST"])
def actors(page_nr):
    # get all entrance from DB
    all_actors = Actor.query.order_by(Actor.id).all()
    per_page = request.args.get("items", 5, type=int)
    current_page = request.args.get("page", 1, type=int)

    actor_count = len(all_actors)

    # Calculate how many items to be dispalyed on the page
    start = per_page * (current_page - 1)
    end = min(start + per_page, actor_count)
    actors = all_actors[start:end]
    mess = ""
    if len(actors) == 0:
        mess = "Warning message: no more actors"

    return render_template("actors/items.html", actors=actors, current_page=current_page, per_page=per_page, mess=mess)


def to_list(dbstring):
    dbstring = dbstring.strip("'][")
    li = dbstring.split(", ")
    result = []
    for item in li:
        result.append((item[1:-1]))
    return result


@actors_blueprint.route("/actors/<int:id>")
def show(id):
    item = Actor.query.get(id)
    filmography_name = item.filmography_movie_name
    filmography_url = item.filmography_url
    filmography = [x for x in zip(to_list(filmography_name), to_list(filmography_url))]
    return render_template("/actors/show.html", actor={"id": item.id, "name": item.name, "filmography": filmography})


@actors_blueprint.route("/actors/new")
def new():
    return render_template("/actors/new.html")


@actors_blueprint.route("/actors/new", methods=["POST"])
def create():
    actor = Actor()
    data = {
        "name": request.form.get("name"),
        "url": request.form.get("url"),
        "filmography_movie_name": request.form.get("filmography_movie_name"),
        "filmography_url": request.form.get("filmography_url"),
    }

    try:
        for item in actor_headers:
            setattr(actor, item, str(data.get(str(item))))

    except AssertionError as err:
        flash("Attention is required")
        return render_template("/actors/new.html", err=err)
    else:
        db.session.add(actor)
        db.session.flush()
        db.session.commit()

    flash("Successful actor insertion!")
    return render_template("/actors/new.html")


@actors_blueprint.route("/actors/<int:id>/edit")
def edit(id):
    item = Actor.query.get(id)
    return render_template("/actors/edit.html", actor=item)


@actors_blueprint.route("/actors/<int:id>", methods=["POST"])
def update(id):
    actor = Actor.query.get(id)
    data = {
        "name": request.form.get("name"),
        "url": request.form.get("url"),
        "filmography_movie_name": request.form.get("filmography_movie_name"),
        "filmography_url": request.form.get("filmography_url"),
    }

    try:
        for item in actor_headers:
            setattr(actor, item, str(data.get(str(item))))

    except AssertionError as err:
        flash("Attention is required!")
        return render_template("/actors/edit.html", actor=actor, err=err)
        # return redirect(url_for("actors.edit", id=actor.id))
    else:
        db.session.add(actor)
        db.session.flush()
        db.session.commit()
        flash("Success!")
    # return render_template("/actors/show.html", actor=actor)
    return redirect(url_for("actors.show", id=actor.id))


@actors_blueprint.route("/actors/upload")
def upload_page():
    return render_template("/actors/upload.html")


@actors_blueprint.route("/actors/upload", methods=["POST"])
def upload():
    # messg = ""
    # check if the post request has the file part
    if "file" not in request.files or request.files["file"].filename == "":
        flash("No file part")
        # return redirect("/movies/upload")
        return render_template("/actors/upload.html")

    file = request.files["file"]

    if file and allowed_file(file.filename):
        for row in file.readlines():
            temp = json.loads(row)
            actor = Actor()
            for item in actor_headers:
                try:
                    setattr(actor, item, str(temp.get(str(item))))
                except AssertionError as err:
                    flash("Attention is required!")
                    return render_template("/actors/upload.html", err=err)

            db.session.add(actor)
        db.session.flush()
        db.session.commit()

        flash("File uploaded successfully!")
    else:
        flash("Unallowed file type")

    return redirect(url_for("actors.upload_page"))

src/presenter/controllers/home.py
from flask import Flask, Blueprint, jsonify, render_template, url_for, request, redirect, flash
from werkzeug.utils import secure_filename
from presenter.services.search import SearchItem

import os
import ipdb


home_blueprint = Blueprint("home", __name__)


@home_blueprint.route("/", methods=["GET", "POST"])
def index():
    return render_template("index.html")


@home_blueprint.route("/results/", methods=["GET", "POST"])
def search_results():
    display = False
    search_string = request.args.get("q")
    movies = []
    actors = []
    service = SearchItem()
    results = service.search(search_string)

    per_page = request.args.get("items", 5, type=int)
    current_page = request.args.get("page", 1, type=int)

    count = len(results)
    start = per_page * (current_page - 1)
    end = min(start + per_page, count)
    movies = movies[start:end]
    actors = actors[start:end]

    mess = ""
    if len(results) <= per_page:
        display = True
    elif len(movies) == 0:
        mess = "Error message, no more items"

    return render_template(
        "services/search_results.html",
        results=results,
        current_page=current_page,
        items_per_page=per_page,
        search_string=search_string,
        display=display,
        mess=mess,
    )

    # return render_template("services/search_results.html", results=results)


# @services_blueprint.route("/results/")
# def search():
#     search_string = request.args.get("q")
#     count = 0
#     movies = []
#     actors = []
#     for item in (Movie, Actor):
#         if item == Movie:
#             movies.extend(Movie.query.filter(Movie.title.like("%" + search_string + "%")).all())
#             count += len(movies)

#         if item == Actor:
#             actors.extend(Actor.query.filter(Actor.name.like("%" + search_string + "%")).all())
#             count += len(actors)

#     per_page = request.args.get("items", 5, type=int)
#     current_page = request.args.get("page", 1, type=int)
#     # count = len(movies) + len(actors)
#     start = per_page * (current_page - 1)
#     end = min(start + per_page, count)
#     movies = movies[start:end]
#     actors = actors[start:end]
#     mess = ""
#     results = {
#         "movies": movies,
#         "actors": actors,
#     }
#     if count == 0:
#         mess = "Error message, no more items"
#     return render_template(
#         "services/search_results.html",
#         results=results,
#         current_page=current_page,
#         items_per_page=per_page,
#         mess=mess,
#         search_string=search_string,
#     )

src/presenter/controllers/users.py
from flask import Flask, Blueprint, session, jsonify, render_template, url_for, request, redirect, flash
import ipdb
from presenter.models.user import User
from presenter.app import db


users_blueprint = Blueprint("users", __name__)


@users_blueprint.route("/login")
def login_form():
    return render_template("/forms/login.html")


@users_blueprint.route("/login", methods=["POST"])
def login():
    try:
        username = request.form.get("username")
        password = request.form.get("password")

    except AssertionError as error:
        return render_template("login.html", error=error)
    else:
        # user = User.query.get(username)
        user = User.query.filter_by(username=username).first()
        # ipdb.set_trace()
        if user.check_password(password):
            flash("You are logged in", "success")
            session["logged_in"] = user.username
            return redirect(url_for("home.index"))


@users_blueprint.route("/logout")
def logout():
    session.pop("logged_in", None)
    flash("Logged out successfully")
    return redirect(url_for("home.index"))


@users_blueprint.route("/register")
def register_form():
    return render_template("/forms/register.html")


@users_blueprint.route("/register", methods=["POST"])
def register():
    if session.get("logged_in"):
        flash("Logout first")
        return render_template("home.index")
    else:
        try:
            username = request.form.get("username")
            email = request.form.get("email")
            password = request.form.get("password")
            re_password = request.form.get("re_password")
        except AssertionError as error:
            return render_template("/forms/register.html", error=error)
        else:
            if password == re_password:
                check_user = User.query.filter_by(username=username).first()
                if check_user == None:
                    user = User(username, email, password)
                    db.session.add(user)
                    db.session.flush()
                    db.session.commit()
                    flash("Successfully registered!")
                    return redirect(url_for("home.index"))
                else:
                    flash("The username is already taken")
                    return render_template("/forms/register.html")

src/presenter/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title> {% block title %}Home page{% endblock %} </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body> 

    <div class="navbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{{ url_for('home.index') }}" class="active">Home</a>
            </li>
            <li>
                <a href="{{ url_for('movies.movies') }}" class="nav-link">Movies</a>
            </li>
            <li>
                <a href="{{ url_for('movies.create') }}" class="nav-link">Add Movie</a>
            </li>
               

            <li>
                <a href="{{ url_for('actors.actors') }}" class="nav-link">Actors</a>
            </li>
            <li>
                <a href="{{ url_for('actors.new') }}" class="nav-link">Add Actor</a>
            </li>
            <li>
                <a href="{{ url_for('movies.upload') }}" class="nav-link">Upload JOSN</a>
            </li>

        </ul>
    </div>
    
    <div class="parent">
        <div class="navbar-nav child">
            <form method="GET" enctype="multipart/form-data" action="{{url_for('home.search_results')}}">
                <label for="search">Search :</label>
                <input type="search" name="q">
                <input type="submit" value="submit">
            </form>  
        </div>
        {% if session.get("logged_in") %}
        <div style="float:right">
            <div class="child nav-item">
                    {{ session.get("logged_in") }}
            </div>
            <div class="child nav-item">
                <a href="{{url_for('users.logout')}}">logout</a>
            </div>
        </div>
        {% else %}
            <div class="child nav-item {{ 'active' if active_page == 'login' }}">
                    <a href="{{ url_for('users.login') }}">Login</a>
            </div>
            
            <div class="child nav-item {{ 'active' if active_page == 'login' }}">
                    <a href="{{ url_for('users.register') }}">Register</a>
            </div>
        {% endif %}
    </div>
    <div class="center">
    {% block content %} 
    {% with messages = get_flashed_messages() %}
      <div class=flashes>
        {% if messages %}
          <ul>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
          </ul>
        {% endif %}
      </div>
    {% endwith %}
        {# =========== Index Section ======== #}
        <a href="{{ url_for('movies.movies') }}">The whole movie list</a><br>
        <a href="{{ url_for('movies.create') }}">Add Movie</a><br>
        <a href="{{ url_for('actors.actors') }}">Actors List</a><br>
        <a href="{{ url_for('actors.new') }}">Add Actor</a><br>
        <a href="{{ url_for('movies.upload') }}">Upload Movie JSON</a><br>
        <a href="{{ url_for('actors.upload') }}">Upload Actor JSON</a><br>
        

        <img src="{{ url_for('static', filename='images/test.jpg') }}" width="70%" height="70%">
        {% if messg %}
            <br>Upload error: {{ messg }}
        {% endif %}
        

    {% endblock %}
    </div>
</body>
</html>