src/presenter/controllers/movies.py
from flask import Flask, Blueprint, jsonify, render_template, url_for, request, redirect, flash
from werkzeug.utils import secure_filename

import os
import ipdb
import json

movies_blueprint = Blueprint("movies", __name__)

from presenter.app import app, db, ALLOWED_EXTENSIONS, UPLOAD_FOLDER
from presenter.models.movie import Movie


headers = [
    "genre",
    "date_of_scraping",
    "director",
    "rating",
    "release_year",
    "title",
    "top_cast",
    "url",
    "image_urls",
    "images",
]


def to_list(dbstring):
    dbstring = dbstring.strip("'][")
    li = dbstring.split(", ")
    result = []
    for item in li:
        if item.startswith("\"['"):
            result.append((item[3:-1]))
        elif item.endswith("']\""):
            result.append((item[1:-3]))
        else:
            result.append((item[1:-1]))
    return result


def allowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


@movies_blueprint.route("/movies/")
def movies():
    # get all entries from DB
    all_movies = Movie.query.order_by(Movie.id).all()

    per_page = request.args.get("items", 5, type=int)
    current_page = request.args.get("page", 1, type=int)

    movie_count = len(all_movies)

    # Calculate how many items to be dispalyed on the page
    start = per_page * (current_page - 1)
    end = min(start + per_page, movie_count)
    movies = all_movies[start:end]
    mess = ""
    if len(movies) == 0:
        mess = "Error message, no more items"

    return render_template(
        "movies/items.html", movies=movies, current_page=current_page, items_per_page=per_page, mess=mess
    )


@movies_blueprint.route("/movies/results/")
def search_item():

    search_string = request.args.get("q")

    try:
        assert len(search_string) > 1
        # return redirect(url_for("movies.search"))

    except AssertionError as warning:
        return redirect(url_for("home.index"))
    else:
        search_result = Movie.query.filter(Movie.title.like("%" + search_string + "%")).all()
        per_page = request.args.get("items", 5, type=int)
        current_page = request.args.get("page", 1, type=int)

        movie_count = len(search_result)
        # Calculate how many items to be dispalyed on the page
        start = per_page * (current_page - 1)
        end = min(start + per_page, movie_count)
        movies = search_result[start:end]
        mess = ""
        if len(movies) == 0:
            mess = "Error message, no more items"
        return render_template(
            "movies/results.html",
            movies=movies,
            current_page=current_page,
            items_per_page=per_page,
            mess=mess,
            search_string=search_string,
        )


@movies_blueprint.route("/movies/new", methods=["GET", "POST"])
def create():
    movie = Movie()

    if request.method == "POST":
        try:
            title = request.form.get("title")
            genre = request.form.get("genre")
            rating = request.form.get("rating")
            url = request.form.get("url")
            date_of_scraping = request.form.get("date_of_scraping")
            director = request.form.get("director")
            release_year = request.form.get("release_year")
            top_cast = request.form.get("top_cast")
            image_urls = request.form.get("image_urls")
            images = request.form.get("images")

            movie.title = title
            movie.genre = genre
            movie.rating = rating
            movie.url = url
            movie.date_of_scraping = date_of_scraping
            movie.director = director
            movie.release_year = release_year
            movie.top_cast = top_cast
            movie.image_urls = image_urls
            movie.images = images
        except AssertionError as err:
            return render_template("/movies/new.html", err=err)
        else:
            db.session.add(movie)
            db.session.flush()
            db.session.commit()
            return render_template("home/index.html")

    return render_template("movies/new.html", new_movie=movie)


@movies_blueprint.route("/movies/<int:id>")
def show(id):
    item = Movie.query.get(id)
    movie = {
        "id": item.id,
        "title": item.title,
        "genre": to_list(item.genre),
        "date_of_scraping": item.date_of_scraping,
        "director": item.director,
        "rating": item.rating,
        "release_year": item.release_year,
        "top_cast": to_list(item.top_cast),
        "url": item.url,
        "image_urls": item.image_urls,
        "images": item.images,
    }
    return render_template("/movies/show.html", movie=movie)


@movies_blueprint.route("/movies/<int:id>", methods=["POST"])
def update(id):
    item = Movie.query.get(id)
    try:
        title = request.form.get("title")
        genre = request.form.get("genre")
        rating = request.form.get("rating")
        url = request.form.get("url")
        date_of_scraping = request.form.get("date_of_scraping")
        director = request.form.get("director")
        release_year = request.form.get("release_year")
        top_cast = request.form.get("top_cast")
        image_urls = request.form.get("image_urls")
        images = request.form.get("images")

        item.title = title
        item.genre = genre
        item.rating = rating
        item.url = url
        item.date_of_scraping = date_of_scraping
        item.director = director
        item.release_year = release_year
        item.top_cast = top_cast
        item.image_urls = image_urls
        item.images = images
    except AssertionError as err:
        flash("Your attention is required")
        return render_template("/movies/edit.html", movie=item, err=err)
        # return redirect(url_for("movies.edit", id=item.id, err=err))
    else:
        db.session.flush()
        db.session.commit()
        flash("Successfully registered!")
        return redirect(url_for("movies.show", id=item.id))
    # movie_url = "/movies/" + str(id) + "show.html"
    # return redirect(url_for("movies.edit", id=item.id))


@movies_blueprint.route("/movies/<int:id>/edit", methods=["GET", "POST"])
def edit(id):
    item = Movie.query.get(id)
    return render_template("/movies/edit.html", movie=item)


@movies_blueprint.route("/movies/upload")
def upload_page():
    return render_template("/movies/upload.html")


# delete from movies where genre is null
@movies_blueprint.route("/movies/upload", methods=["POST"])
def upload():
    # messg = ""
    # check if the post request has the file part
    if "file" not in request.files or request.files["file"].filename == "":
        # messg = "No file part"
        flash("No file part")
        # return redirect(request.url)
        # return redirect("/movies/upload")
        return render_template("/movies/upload.html")
    file = request.files["file"]

    if file and allowed_file(file.filename):
        for row in file.readlines():
            temp = json.loads(row)
            movie = Movie()
            for item in headers:
                try:
                    setattr(movie, item, str(temp.get(str(item))))
                    # ipdb.set_trace()
                    # movie.title = temp.get("title")
                except AssertionError as err:
                    flash("Attention is required!")
                    return render_template("/movies/upload.html", err=err)
            if movie.errors:
                return render_template("/movies/upload.html", err=movie.errors)

            db.session.add(movie)
        db.session.flush()
        db.session.commit()

        # filename = secure_filename(file.filename)
        # file.save(os.path.join(app.config["UPLOAD_FOLDER"], filename))
        print(file)
        # ipdb.set_trace()
        flash("File uploaded successfully!")
        # messg = "Successfully uploaded file"
    else:
        flash("Unallowed file type")
        # messg = "Unallowed file type"

    # return redirect(url_for("movies.upload"))

    return render_template("/movies/upload.html")

src/presenter/templates/movies/edit.html
{% extends 'index.html' %}

{% block title %}New Movie{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
<div class=flashes>
    {% if messages %}
      <ul >
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
      </ul>
    {% endif %}
</div>
{% endwith %}

    <h1>Edit Movie ID {{ movie.id }}</h1>
    <span style="color:red">
        {% if err %}
            {{ err }}
        {% endif %}
    </span>

<div class="content">    
    <form method="post" action="{{ url_for('movies.update', id=movie.id) }}">
        <label for="title">Title</label>
        <br>
        <input type="text" name="title"
               placeholder="Message title"
               value="{{ movie['title'] }}"></input>
        <br>

        <input type="text" name="genre"
               placeholder="Category type"
               value="{{ movie['genre'] }}"></input>
        <br>
        <input type="text" name="rating"
               placeholder="Rating"
               value="{{ movie['rating'] }}"></input>
        <br>
        <input type="text" name="url"
               placeholder="Movie URL"
               value="{{ movie['url'] }}"></input>
        <br>
               
        <input type="text" name="date_of_scraping"
               placeholder="Record Date"
               value="{{ movie['date_of_scraping'] }}"></input>
        <br>

        <input type="text" name="director"
               placeholder="Director Name"
               value="{{ movie['director'] }}"></input>
        <br>

        <input type="text" name="release_year"
               placeholder="Release Year"
               value="{{ movie['release_year'] }}"></input>
        <br>

        <input type="text" name="top_cast"
               placeholder="Top Cast"
               value="{{ movie['top_cast'] }}"></input>
        <br>

        <input type="text" name="image_urls"
               placeholder="Image URL"
               value="{{ movie['image_urls'] }}"></input>
        <br>

        <input type="text" name="images"
               placeholder="Local Image URL"
               value="{{ movie['images'] }}"></input>
        <br>
        <br>
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

{#                  
<textarea name="content"
placeholder="Message content"
rows="15"
cols="60"
>{{ request.form['content'] }}</textarea>
 #}

src/presenter/templates/movies/items.html
{% extends 'index.html' %}

{# set active_page = 'home' #}

{% block title %}IMDB Movies List{% endblock %}

{% block content %}
<div class="navbar-nav">
	<ul>
	    {% if current_page == 1 %}
	        <li style="float:left">
	        	<a  href="#">Previous</a></li>
	    {% else %}
	        <li style="float:left">
	        	<a href="{{ url_for('movies.movies', page=current_page - 1, items=items_per_page) }}">Previous</a></li>
	    {% endif %}
	        <li style="float:right">
	        	<a class="button-next" href="{{ url_for('movies.movies', page=current_page + 1, items=items_per_page) }}">Next</a></li>
	</ul>
</div>


	{{ mess }}
    {% for movie in movies %}
    <div class="center">
    	<ul id="movies">
	        <li class="movie-item"> {{movie.id}} <a href="{{ movie.id }}">{{ movie.title }}</a></li>
	        {% set imgfile = "images/" + movie.images[1:-1] %}
	        <img src="{{ url_for('static', filename=imgfile) }}" alt="idmb movie image" class='center'>
	        <hr>
	    </ul>
	    <br>
	</div>
	{% endfor %}
{% endblock %}

src/presenter/templates/movies/new.html
{% extends 'index.html' %}

{% block title %}New Movie{% endblock %}

{% block content %}

	<h1>All the fields are mandatory</h1>
	<span style="color:red">
		{% if err %} {{ err }} {% endif %}
	</span>
    
    <form method="post" action="{{ url_for('movies.create') }}">
	    <label for="title">Title</label>
	    <br>
	    <input type="text" name="title"
	           placeholder="Message title"
	           value="{{ request.form['title'] }}"></input>
	    <br>

	    <input type="text" name="genre"
	           placeholder="Category type"
	           value="{{ request.form['genre'] }}"></input>
	    <br>
	    <input type="text" name="rating"
	           placeholder="Rating"
	           value="{{ request.form['rating'] }}"></input>
	    <br>
	    <input type="text" name="url"
	           placeholder="Movie URL"
	           value="{{ request.form['url'] }}"></input>
	    <br>
	           
	    <input type="text" name="date_of_scraping"
	           placeholder="Record Date"
	           value="{{ request.form['date_of_scraping'] }}"></input>
	    <br>

	    <input type="text" name="director"
	           placeholder="Director Name"
	           value="{{ request.form['director'] }}"></input>
	    <br>

	    <input type="text" name="release_year"
	           placeholder="Release Year"
	           value="{{ request.form['release_year'] }}"></input>
	    <br>

	    <input type="text" name="top_cast"
	           placeholder="Top Cast"
	           value="{{ request.form['top_cast'] }}"></input>
	    <br>

	    <input type="text" name="image_urls"
	           placeholder="Image URL"
	           value="{{ request.form['image_urls'] }}"></input>
	    <br>

	    <input type="text" name="images"
	           placeholder="Local Image URL"
	           value="{{ request.form['images'] }}"></input>
	    <br>
	    <br>
	    <button type="submit">Submit</button>
    </form>

{% endblock %}

{# 	    			
<textarea name="content"
placeholder="Message content"
rows="15"
cols="60"
>{{ request.form['content'] }}</textarea>
 #}

src/presenter/templates/movies/results.html
{% extends 'index.html' %}

{# set active_page = 'home' #}

{% block title %}IMDB Movies List{% endblock %}

{% block content %}
<div class="navbar-nav">
    <ul>
        {% if current_page == 1 %}
            <li style="float:left">
                <a  href="#">Previous</a></li>
        {% else %}
            <li style="float:left">
                <a href="{{ url_for('movies.search_item', q=search_string, page=current_page - 1, items=items_per_page) }}">Previous</a></li>
        {% endif %}
            <li style="float:right">
                <a class="button-next" href="{{ url_for('movies.search_item', q=search_string, page=current_page + 1, items=items_per_page) }}">Next</a></li>
    </ul>
</div>


    {{ mess }}
    {% for movie in movies %}
    <div class="center">
        <ul id="movies">
            <li class="movie-item"> {{movie.id}} <a href="{{ movie.id }}">{{ movie.title }}</a></li>
            {% set imgfile = "images/" + movie.images[1:-1] %}
            <img src="{{ url_for('static', filename=imgfile) }}" alt="idmb movie image" class='center'>
            <hr>
        </ul>
        <br>
    </div>
    {% endfor %}
{% endblock %}

src/presenter/templates/movies/show.html
{% extends 'index.html' %}

{% block title %}Movie Info{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
<div class=flashes>
    {% if messages %}
      <ul >
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
  {% endif %}
</div>
{% endwith %}

<div class="show">
    <div>
      <span class="movie-item"> <a href="{{ url_for('movies.edit', id=movie.id) }}"><i>Edit Movie</i></a></span>
  </div>
    <div>
      
      <h1>{{ movie.title }}</h1>
      <h3>Movie Info</h3>
      {#
      {% for item in movie.__dict__.items() %}
        <p>{{ item }}} </p>
      {% endfor %}
      #}
      <ul>
      {% for key, value in movie.items() %}
        <p>{% if value is string %}
            <b>{{ key }}</b>: {{value}}</p>
        <p>{% elif value is sequence %}
            <b>{{ key }}</b>:
            {% for item in value %}
              <li>{{item}}</li>
            {% endfor %} </p>
          {% endif %}
      {% endfor %}
      </ul>

  </div>

</div>
{% endblock %}

src/presenter/templates/movies/upload.html
{% extends 'index.html' %}

{% block title %}Load a file{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
  <div class=flashes>
    {% if messages %}
      <ul>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endwith %}

  {% if err %}
    <span style="color:red"> {{ err }} </span>
  {% endif %}

<div>
	<h1>Movies: Upload new File</h1>
	    <form method="POST" enctype="multipart/form-data" action="{{ url_for('movies.upload') }}">
	      <input type="file" name="file">
	      <input type="submit" value="Upload">
	    </form>
</div>
{% endblock %}