src/presenter/models/actor.py
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Index
from sqlalchemy.orm import relationship, validates
from presenter.app import db
import datetime


class Actor(db.Model):
    __tablename__ = "actors"
    id = Column(Integer, primary_key=True, unique=True, autoincrement=True)
    name = Column(String(255), nullable=False)
    url = Column(String(255), nullable=True)
    filmography_movie_name = Column(String(255), nullable=True)
    filmography_url = Column(String(255), nullable=True)

    def __repr__(self):
        return "<Actor id=%s> %s %s" % (self.id, self.name, self.url)

    @validates(
        "name",
        "url",
        "filmography_movie_name",
        "filmography_url",
    )
    def validates_fields(self, keys, values):
        # ipdb.set_trace()
        if keys == "name":
            assert values != "", "Name is missing"
        if keys == "url":
            assert values != "", "URL is required"
        if keys == "filmography_movie_name":
            assert values != "", "Filmography: Movie name is required"
        if keys == "filmography_url":
            assert values != "", "Filmography: Movie URL is required"

        return values

src/presenter/controllers/actors.py
from flask import Flask, Blueprint, jsonify, render_template, url_for, request, redirect, flash
import ipdb
import json

actors_blueprint = Blueprint("actors", __name__)

from presenter.app import app, db, ALLOWED_EXTENSIONS, UPLOAD_FOLDER
from presenter.models.actor import Actor


actor_headers = ["name", "url", "filmography_movie_name", "filmography_url"]


def allowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


@actors_blueprint.route("/actors/", defaults={"page_nr": 1})
# @actors_blueprint.route("/actors/page=<int:page_nr>&items=<int:item_nr>", methods=["GET", "POST"])
def actors(page_nr):
    # get all entrance from DB
    all_actors = Actor.query.order_by(Actor.id).all()
    per_page = request.args.get("items", 5, type=int)
    current_page = request.args.get("page", 1, type=int)

    actor_count = len(all_actors)

    # Calculate how many items to be dispalyed on the page
    start = per_page * (current_page - 1)
    end = min(start + per_page, actor_count)
    actors = all_actors[start:end]
    mess = ""
    if len(actors) == 0:
        mess = "Warning message: no more actors"

    return render_template("actors/items.html", actors=actors, current_page=current_page, per_page=per_page, mess=mess)


def to_list(dbstring):
    dbstring = dbstring.strip("'][")
    li = dbstring.split(", ")
    result = []
    for item in li:
        result.append((item[1:-1]))
    return result


@actors_blueprint.route("/actors/<int:id>")
def show(id):
    item = Actor.query.get(id)
    filmography_name = item.filmography_movie_name
    filmography_url = item.filmography_url
    filmography = [x for x in zip(to_list(filmography_name), to_list(filmography_url))]
    return render_template("/actors/show.html", actor={"id": item.id, "name": item.name, "filmography": filmography})


@actors_blueprint.route("/actors/new")
def new():
    return render_template("/actors/new.html")


@actors_blueprint.route("/actors/new", methods=["POST"])
def create():
    actor = Actor()
    data = {
        "name": request.form.get("name"),
        "url": request.form.get("url"),
        "filmography_movie_name": request.form.get("filmography_movie_name"),
        "filmography_url": request.form.get("filmography_url"),
    }

    try:
        for item in actor_headers:
            setattr(actor, item, str(data.get(str(item))))

    except AssertionError as err:
        flash("Attention is required")
        return render_template("/actors/new.html", err=err)
    else:
        db.session.add(actor)
        db.session.flush()
        db.session.commit()

    flash("Successful actor insertion!")
    return render_template("/actors/new.html")


@actors_blueprint.route("/actors/<int:id>/edit")
def edit(id):
    item = Actor.query.get(id)
    return render_template("/actors/edit.html", actor=item)


@actors_blueprint.route("/actors/<int:id>", methods=["POST"])
def update(id):
    actor = Actor.query.get(id)
    data = {
        "name": request.form.get("name"),
        "url": request.form.get("url"),
        "filmography_movie_name": request.form.get("filmography_movie_name"),
        "filmography_url": request.form.get("filmography_url"),
    }

    try:
        for item in actor_headers:
            setattr(actor, item, str(data.get(str(item))))

    except AssertionError as err:
        flash("Attention is required!")
        return render_template("/actors/edit.html", actor=actor, err=err)
        # return redirect(url_for("actors.edit", id=actor.id))
    else:
        db.session.add(actor)
        db.session.flush()
        db.session.commit()
        flash("Success!")
    # return render_template("/actors/show.html", actor=actor)
    return redirect(url_for("actors.show", id=actor.id))


@actors_blueprint.route("/actors/upload")
def upload_page():
    return render_template("/actors/upload.html")


@actors_blueprint.route("/actors/upload", methods=["POST"])
def upload():
    # messg = ""
    # check if the post request has the file part
    if "file" not in request.files or request.files["file"].filename == "":
        flash("No file part")
        # return redirect("/movies/upload")
        return render_template("/actors/upload.html")

    file = request.files["file"]

    if file and allowed_file(file.filename):
        for row in file.readlines():
            temp = json.loads(row)
            actor = Actor()
            for item in actor_headers:
                try:
                    setattr(actor, item, str(temp.get(str(item))))
                except AssertionError as err:
                    flash("Attention is required!")
                    return render_template("/actors/upload.html", err=err)

            db.session.add(actor)
        db.session.flush()
        db.session.commit()

        flash("File uploaded successfully!")
    else:
        flash("Unallowed file type")

    return redirect(url_for("actors.upload_page"))

src/presenter/templates/actors/edit.html
{% extends 'index.html' %}

{% block title %}New Actor{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
<div class=flashes>
    {% if messages %}
      <ul >
	      {% for message in messages %}
	        <li>{{ message }}</li>
	      {% endfor %}
      </ul>
	{% endif %}
</div>
{% endwith %}

<h1>Edit Actor ID {{ actor.id }}</h1>


<span style="color:red">
	{% if err %}
		{{ err }}
	{% endif %}
</span>

<div class="content">    
    <form method="post" action="{{ url_for('actors.update', id=actor.id) }}">
	    <label for="name">Name</label>
		    <br>
		    <input type="text" name="name"
		           placeholder="Actor name"
		           value="{{ actor['name'] }}">
		    </input>
		    <br>

		<label for="url">URL</label>
		    <br>
		    <input type="text" name="url"
		           placeholder="Actor URL"
		           value="{{ actor['url'] }}">
		    </input>
		    <br>

		<label for="filmography_movie_name">Filmography Movies</label>
		    <br>
		    <input type="text" name="filmography_movie_name"
		           placeholder="Movies Name"
		           value="{{ actor['filmography_movie_name'] }}">
		    </input>
		    <br>

		<label for="filmography_movie_name">Filmography URL</label>
		    <br>
		    <input type="text" name="filmography_url"
		           placeholder="Movie URL"
		           value="{{ actor['filmography_url'] }}">
		    </input>
		    <br>
		    <br>

	    <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

src/presenter/templates/actors/items.html
{% extends 'index.html' %}

{% block title %}Actors List{% endblock %}

{% block content %}
<div class="navbar-nav">
	<ul>
	    {% if current_page == 1 %}
	        <li style="float:left">
	        	<a  href="#">Previous</a></li>
	    {% else %}
	        <li style="float:left">
	        	<a href="{{ url_for('actors.actors', page=current_page - 1, items=per_page) }}">Previous</a></li>
	    {% endif %}
	        <li style="float:right">
	        	<a class="button-next" href="{{ url_for('actors.actors', page=current_page + 1, items=per_page) }}">Next</a></li>
	</ul>
</div>
<div class="center">
	{{ mess }}
    {% for actor in actors %}
    <div>
    	<ul class="actor">
	        <li class="actor-item">
	        	#{{ actor.id }} Name: 
	        <a href="{{ actor.id }}">{{ actor.name }}</a><br>
	        </li>
	        	Actor IMBD page: 
	        <li class="actor-item">{{ actor.url }}</a></li>
	        {# <li class="actor-item">{{ actor.filmography_movie_name }}</li> #}
	    </ul>
	    <br>
	</div>
	{% endfor %}
</div>
{% endblock %}

src/presenter/templates/actors/new.html
{% extends 'index.html' %}

{% block title %}New Movie{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
<div class=flashes>
    {% if messages %}
      <ul >
	      {% for message in messages %}
	        <li>{{ message }}</li>
	      {% endfor %}
      </ul>
	{% endif %}
{% endwith %}
</div>

	<h1>All the fields are mandatory</h1>
	<span style="color:red">
		{% if err %} {{ err }} {% endif %}
	</span>
    
    <form method="post" action="{{ url_for('actors.create') }}">
	    <label for="name">Name</label>
		    <br>
		    <input type="text" name="name"
		           placeholder="Actor name"
		           value="{{ request.form['name'] }}">
		    </input>
		    <br>

		<label for="url">URL</label>
		    <br>
		    <input type="text" name="url"
		           placeholder="Actor URL"
		           value="{{ request.form['url'] }}">
		    </input>
		    <br>

		<label for="filmography_movie_name">Filmography Movies</label>
		    <br>
		    <input type="text" name="filmography_movie_name"
		           placeholder="Movies Name"
		           value="{{ request.form['filmography_movie_name'] }}">
		    </input>
		    <br>

		<label for="filmography_movie_name">Filmography URL</label>
		    <br>
		    <input type="text" name="filmography_url"
		           placeholder="Movie URL"
		           value="{{ request.form['filmography_url'] }}">
		    </input>
		    <br>
		    <br>

	    <button type="submit">Submit</button>
    </form>

{% endblock %}

{# 	    			
<textarea name="content"
placeholder="Message content"
rows="15"
cols="60"
>{{ request.form['content'] }}</textarea>
 #}

src/presenter/templates/actors/show.html
{% extends 'index.html' %}

{% block title %}Actor Filmography{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
<div class=flashes>
    {% if messages %}
      <ul >
	      {% for message in messages %}
	        <li>{{ message }}</li>
	      {% endfor %}
      </ul>
	{% endif %}
</div>
{% endwith %}

<span style="color:red">
	{% if err %}
		{{ err }}
	{% endif %}
</span>

<div class="center">
    <div class="show">
	    <span> <a href="{{ url_for('actors.edit', id=actor.id) }}"><i>Edit Actor</i></a></span>
    <div>
    <div>
   	
    	<h1>{{ actor.name }}</h1>
    	<h3>Filmography</h3>
    	{% for item in actor.filmography %}
	    	<p>Movie Name: {{ item[0] }} <br>
	    		IBDM Source: <a href="{{ item[1] }}"> {{ item[1] }}  </a> </p>
    	{% endfor %}

	</div>

</div>
{% endblock %}

src/presenter/templates/actors/upload.html
{% extends 'index.html' %}

{% block title %}Load a file{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
  <div class=flashes>
    {% if messages %}
      <ul>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endwith %}

  {% if err %}
    <span style="color:red"> {{ err }} </span>
  {% endif %}

<div>
    <h1>Actors: Upload new File</h1>
        <form method="POST" enctype="multipart/form-data" action="{{ url_for('actors.upload') }}">
          <input type="file" name="file">
          <input type="submit" value="Upload">
        </form>
</div>
{% endblock %}